In [25]:
import numpy as np
import pandas as pd

In [26]:
df=pd.read_csv("C:/Users/A/diabetes.csv")
df

,Unnamed: 0,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,0,2,138,62,35,0,33.6,0.127,47,0
1,1,0,84,82,31,125,38.2,0.233,23,0
2,2,0,145,0,0,0,44.2,0.630,31,0
3,3,0,135,68,42,250,42.3,0.365,24,0
4,4,1,139,62,41,480,40.7,0.536,21,0
...,...,...,...,...,...,...,...,...,...,...
1334,1974,1,153,82,42,485,40.6,0.687,23,1
1335,1975,8,188,78,0,0,47.9,0.137,43,1
1336,1976,7,152,88,44,0,50.0,0.337,36,1
1337,1977,2,99,52,15,94,24.6,0.637,21,1
1338,1978,1,109,56,21,135,25.2,0.833,23,1

In [27]:
df.describe()

,Unnamed: 0,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,1339.000000,1339.000000,1339.000000,1339.000000,1339.000000,1339.000000,1339.000000,1339.000000,1339.000000,1339.000000
mean,951.263630,3.752801,121.083645,69.126960,20.844660,79.851382,32.184615,0.474176,33.007468,0.451083
std,667.597467,3.325983,31.855764,19.224199,16.062511,113.512132,8.128558,0.328254,11.703101,0.497787
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,334.500000,1.000000,99.500000,62.000000,0.000000,0.000000,27.400000,0.245000,24.000000,0.000000
50%,702.000000,3.000000,117.000000,72.000000,23.000000,32.000000,32.300000,0.378000,29.000000,0.000000
75%,1608.500000,6.000000,141.000000,80.000000,32.500000,128.500000,36.800000,0.629500,40.000000,1.000000
max,1978.000000,17.000000,199.000000,122.000000,110.000000,744.000000,80.600000,2.420000,81.000000,1.000000

In [28]:
df.shape

(1339, 10)

In [29]:
df.isnull().sum()

Unnamed: 0                  0
Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [30]:
df.duplicated().sum()

np.int64(0)

In [31]:
df=df.drop_duplicates()

In [32]:
df.duplicated().sum()

np.int64(0)

In [33]:
category_column=df.select_dtypes(include=['object']).columns.tolist()
category_column

[]

In [36]:
df.to_csv("C:/Users/A/Diabetes.csv",index=False)